import { User } from '../folder-interfaces/users';

export const USERS: User[] = [
  {
    userId: 1,
    personId: 'P001',
    salutation: 'Herr',
    letter: 'A',
    firstName: 'Max',
    preName: 'Johann',
    adress: 'Musterstraße 12',
    zip: 9495,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Triesen',
    country: 'Liechtenstein',
    email: 'max.mustermann@example.com',
    tel: '+423 123 4567',
    remarks: 'VIP Kunde',
    role: 1,
    admissionDate: new Date('2024-01-15'),
    checkOutDate: new Date('2024-02-15'),
    admissionDateDispaly: '15.01.2024',
    checkOutDateDispaly: '15.02.2024',
    loginName: 'maxm',
    password: 'securePass123',
    hasPaid: true,
    paidDate: new Date('2024-01-20'),
    personAccessList: 'Admin,User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 2,
    personId: 'P002',
    salutation: 'Frau',
    letter: 'B',
    firstName: 'Anna',
    preName: 'Maria',
    adress: 'Bahnhofstraße 5',
    zip: 8000,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Zürich',
    country: 'Schweiz',
    email: 'anna.maria@example.com',
    tel: '+41 44 987 6543',
    remarks: 'Neue Kundin',
    role: 2,
    admissionDate: new Date('2024-03-01'),
    checkOutDate: new Date('2024-03-10'),
    admissionDateDispaly: '01.03.2024',
    checkOutDateDispaly: '10.03.2024',
    loginName: 'annam',
    password: 'pass456',
    hasPaid: false,
    paidDate: new Date('2024-03-10'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 3,
    personId: 'P003',
    salutation: 'Herr',
    letter: 'C',
    firstName: 'Peter',
    preName: 'Klaus',
    adress: 'Hauptstraße 42',
    zip: 80331,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'München',
    country: 'Deutschland',
    email: 'peter.klaus@example.com',
    tel: '+49 89 123 4567',
    remarks: 'Stammkunde',
    role: 1,
    admissionDate: new Date('2023-06-20'),
    checkOutDate: new Date('2024-06-20'),
    admissionDateDispaly: '20.06.2023',
    checkOutDateDispaly: '20.06.2024',
    loginName: 'peterk',
    password: 'pass789',
    hasPaid: true,
    paidDate: new Date('2024-01-10'),
    personAccessList: 'Admin,User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 4,
    personId: 'P004',
    salutation: 'Frau',
    letter: 'D',
    firstName: 'Sophie',
    preName: 'Elisabeth',
    adress: 'Schillerstraße 8',
    zip: 69115,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Heidelberg',
    country: 'Deutschland',
    email: 'sophie.e@example.com',
    tel: '+49 6221 456 7890',
    remarks: 'Aktive Kundin',
    role: 2,
    admissionDate: new Date('2024-02-14'),
    checkOutDate: new Date('2024-05-14'),
    admissionDateDispaly: '14.02.2024',
    checkOutDateDispaly: '14.05.2024',
    loginName: 'sophiee',
    password: 'secure456',
    hasPaid: true,
    paidDate: new Date('2024-02-20'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 5,
    personId: 'P005',
    salutation: 'Herr',
    letter: 'E',
    firstName: 'Thomas',
    preName: 'Michael',
    adress: 'Ringstraße 15',
    zip: 1010,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Wien',
    country: 'Österreich',
    email: 'thomas.michael@example.com',
    tel: '+43 1 234 5678',
    remarks: 'Internationaler Kunde',
    role: 2,
    admissionDate: new Date('2023-11-05'),
    checkOutDate: new Date('2024-11-05'),
    admissionDateDispaly: '05.11.2023',
    checkOutDateDispaly: '05.11.2024',
    loginName: 'thomasmi',
    password: 'michel123',
    hasPaid: false,
    paidDate: new Date('2024-02-28'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 6,
    personId: 'P006',
    salutation: 'Frau',
    letter: 'F',
    firstName: 'Julia',
    preName: 'Katharina',
    adress: 'Marktplatz 3',
    zip: 6900,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Lugano',
    country: 'Schweiz',
    email: 'julia.k@example.com',
    tel: '+41 91 234 5678',
    remarks: 'Premium Mitglied',
    role: 1,
    admissionDate: new Date('2023-04-10'),
    checkOutDate: new Date('2025-04-10'),
    admissionDateDispaly: '10.04.2023',
    checkOutDateDispaly: '10.04.2025',
    loginName: 'juliakath',
    password: 'kath1234',
    hasPaid: true,
    paidDate: new Date('2024-03-05'),
    personAccessList: 'Admin,User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 7,
    personId: 'P007',
    salutation: 'Herr',
    letter: 'G',
    firstName: 'Robert',
    preName: 'Franz',
    adress: 'Dorfstraße 27',
    zip: 6900,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Schaan',
    country: 'Liechtenstein',
    email: 'robert.franz@example.com',
    tel: '+423 234 5678',
    remarks: 'Treuer Kunde',
    role: 2,
    admissionDate: new Date('2022-09-12'),
    checkOutDate: new Date('2025-09-12'),
    admissionDateDispaly: '12.09.2022',
    checkOutDateDispaly: '12.09.2025',
    loginName: 'robertfr',
    password: 'franz2022',
    hasPaid: true,
    paidDate: new Date('2024-01-15'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 8,
    personId: 'P008',
    salutation: 'Frau',
    letter: 'H',
    firstName: 'Martina',
    preName: 'Andrea',
    adress: 'Kapellenweg 91',
    zip: 9000,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'St. Gallen',
    country: 'Schweiz',
    email: 'martina.andrea@example.com',
    tel: '+41 71 234 5678',
    remarks: 'Regelmäßige Besucherin',
    role: 2,
    admissionDate: new Date('2024-01-25'),
    checkOutDate: new Date('2024-07-25'),
    admissionDateDispaly: '25.01.2024',
    checkOutDateDispaly: '25.07.2024',
    loginName: 'martinaa',
    password: 'andrea99',
    hasPaid: false,
    paidDate: new Date('2024-02-10'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: true,
    authdata: '',
    token: ''
  },
  {
    userId: 9,
    personId: 'P009',
    salutation: 'Herr',
    letter: 'I',
    firstName: 'Wilhelm',
    preName: 'Bernd',
    adress: 'Waldstraße 44',
    zip: 28195,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Bremen',
    country: 'Deutschland',
    email: 'wilhelm.bernd@example.com',
    tel: '+49 421 567 8901',
    remarks: 'Business Kunde',
    role: 1,
    admissionDate: new Date('2023-07-03'),
    checkOutDate: new Date('2024-07-03'),
    admissionDateDispaly: '03.07.2023',
    checkOutDateDispaly: '03.07.2024',
    loginName: 'wilhelmb',
    password: 'bernd456',
    hasPaid: true,
    paidDate: new Date('2024-01-30'),
    personAccessList: 'Admin,User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 10,
    personId: 'P010',
    salutation: 'Frau',
    letter: 'J',
    firstName: 'Cornelia',
    preName: 'Emma',
    adress: 'Blumenweg 12',
    zip: 3011,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Bern',
    country: 'Schweiz',
    email: 'cornelia.emma@example.com',
    tel: '+41 31 345 6789',
    remarks: 'Senior Mitglied',
    role: 2,
    admissionDate: new Date('2022-05-18'),
    checkOutDate: new Date('2025-05-18'),
    admissionDateDispaly: '18.05.2022',
    checkOutDateDispaly: '18.05.2025',
    loginName: 'corneliae',
    password: 'emma2022',
    hasPaid: true,
    paidDate: new Date('2024-03-12'),
    personAccessList: 'User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 11,
    personId: 'P011',
    salutation: 'Herr',
    letter: 'K',
    firstName: 'Hermann',
    preName: 'Walter',
    adress: 'Birkenstraße 77',
    zip: 6800,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Feldkirch',
    country: 'Österreich',
    email: 'hermann.walter@example.com',
    tel: '+43 5522 234 5678',
    remarks: 'Gelegentlicher Kunde',
    role: 2,
    admissionDate: new Date('2024-01-08'),
    checkOutDate: new Date('2024-04-08'),
    admissionDateDispaly: '08.01.2024',
    checkOutDateDispaly: '08.04.2024',
    loginName: 'hermannw',
    password: 'walter88',
    hasPaid: false,
    paidDate: new Date('2024-02-01'),
    personAccessList: 'User',
    active: false,
    mustNotPaid: false,
    authdata: '',
    token: ''
  },
  {
    userId: 12,
    personId: 'P012',
    salutation: 'Frau',
    letter: 'L',
    firstName: 'Gertrude',
    preName: 'Helga',
    adress: 'Eichenweg 33',
    zip: 72764,
    flag: '4/47/Flag_of_Liechtenstein.svg',
    town: 'Reutlingen',
    country: 'Deutschland',
    email: 'gertrude.helga@example.com',
    tel: '+49 7121 678 9012',
    remarks: 'Langjährige Kundin',
    role: 1,
    admissionDate: new Date('2021-08-25'),
    checkOutDate: new Date('2024-08-25'),
    admissionDateDispaly: '25.08.2021',
    checkOutDateDispaly: '25.08.2024',
    loginName: 'gertrudeh',
    password: 'helga321',
    hasPaid: true,
    paidDate: new Date('2024-03-08'),
    personAccessList: 'Admin,User',
    active: true,
    mustNotPaid: false,
    authdata: '',
    token: ''
  }
];
